table dim_date
	lineageTag: e58bbd97-7fd6-4923-9985-7f49388f45f6
	dataCategory: Time

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: ec77317b-d1f7-4b80-bec2-68974f3750fb
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = User

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 79b80ef3-7886-4d80-bfd6-b8db1b3a56cd
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 671d2772-77a6-408c-8c81-eb58fcc6c569
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column quarter
		dataType: string
		lineageTag: 4c44a6e9-76e6-41f5-9912-16cb46fb70dc
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: int64
		formatString: 0
		lineageTag: c2bff8eb-20ef-4a1d-90ef-1446a0de117f
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = User

	column month_name
		dataType: string
		lineageTag: 5f9a1fd5-fe39-4e12-be1e-63bb5793275a
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

	column month_short
		dataType: string
		lineageTag: 21d3bde2-1736-4c5d-a62f-30deab975ab4
		summarizeBy: none
		sourceColumn: month_short
		sortByColumn: month

	column year_month
		dataType: string
		lineageTag: 4532c235-db3a-47de-99a4-f6e78f1d16f5
		summarizeBy: none
		sourceColumn: year_month

	column day
		dataType: int64
		formatString: 0
		lineageTag: 906f1c88-1989-4109-88b6-04742355a994
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = User

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 98166653-1c02-486f-801c-6d9289538b93
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = User

	column day_name
		dataType: string
		lineageTag: 3cb767b0-f372-46f3-a349-858389ca214e
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

	column is_weekend
		dataType: boolean
		lineageTag: 1e4f0380-f6a7-497e-977b-8fc0f3e14ec7
		summarizeBy: none
		sourceColumn: is_weekend

	column is_month_start
		dataType: boolean
		lineageTag: fb6cb035-1d14-4291-b60d-c6fbcbc82140
		summarizeBy: none
		sourceColumn: is_month_start

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: 1e4d05f2-f283-4301-bdea-99e5f030407c
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = User

	partition dim_date = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Columns = 14, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"date_id", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month", Int64.Type}, {"month_name", type text}, {"month_short", type text}, {"year_month", type text}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}, {"is_month_start", type logical}, {"fiscal_year", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

